### ISSUE TITLE
Serialize ObjectListField 

### ISSUE THREAD

**Issue by SalimAnsari1808** [sinarezaei/pykson#9]
Using pykson file to Serialize my request payload

Sample Json file:
{
  "userId": "string",
  "collectionOfIsbns": [
    {
      "isbn": "string"
    }
  ]
}

Classes created using pykson lib

class add_books_json(JsonObject):
    isbn = StringField()

class addBookRequest(JsonObject):
    userId = StringField()
    collectionOfIsbns = ObjectListField(add_books_json)

Now i want to assign values to create json file file.am using below code to do this
        booksjson = add_books_json()
        booksjson.isbn = "9781449337711"

        book_require_json = json.loads(pykson.Pykson().to_json(booksjson))

        add_Books_Request = addBookRequest()
        add_Books_Request.userId = self.getuser_id()
        add_Books_Request.collectionOfIsbns =  pykson.ObjectField(book_require_json)

        payloadBody = pykson.Pykson().to_json(add_Books_Request)

i know am doing it wrong for collectionOfIsbns field. Can you please help me on this to create json payload as mentioned above using pykson lib

**Comment by sinarezaei** [comment]
Just use the value instead of creating a pykson.ObjectField
```
booksjson = add_books_json()
booksjson.isbn = "9781449337711"

add_Books_Request = addBookRequest()
add_Books_Request.userId = self.getuser_id()
add_Books_Request.collectionOfIsbns =  [booksjson]

payloadBody = pykson.Pykson().to_json(add_Books_Request)
```

**Comment by SalimAnsari1808** [comment]
Thanks a lot. it worked for me.
